# Production-specific configuration
baseurl: ""
url: "https://unraid-api-docs.pages.dev"

# Disable future posts
future: false

# Enable compression
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [html, head, body]
  
# Exclude development-specific files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
