title: Unraid API Documentation
description: Documentation for the Unraid API Python library
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Aux links for the upper right navigation
aux_links:
  "Unraid API on GitHub":
    - "https://github.com/domalab/unraid-api"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2025 domalab. Distributed under an <a href=\"https://github.com/domalab/unraid-api/blob/main/LICENSE\">MIT license.</a>"

# Heading anchor links
heading_anchors: true

# Google Analytics
ga_tracking:
ga_tracking_anonymize_ip: true

# Enable or disable the site search
search_enabled: true

# Set the search token separator
search_tokenizer_separator: /[\s/]+/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections for docs
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_fold: true
